[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Altaks"]
license = "MIT"

[workspace]
resolver = "3"
members = ["apps/main", "libs/main_lib"]

[workspace.dependencies]
main_lib = { path = "libs/main_lib" }
